package com.nettydemo.not_used.entities;

import java.io.Serializable;

/**
 * Wrapper for messages sent from client to server
 * Contains header and object that being sent (message body)
 */
public class RequestMessage implements Serializable, Cloneable {
    /**
     * Client IP
     */
    private String senderIp;
    /**
     * Command what to do with this object on server side
     */
    private String serviceId;
    /**
     * Unique code of the message. It is generated by Utils singleton object
     */
    private String messageGuid;
    /**
     * Date and time when the object was sent
     */
    private long requestTime;
    /**
     * Content. The object that is being sent to the server
     */
    private Object messageBody;
    /**
     * Class of the content above. This field is optional, as we can
     * detect content's class by .getClass or instanceOf methods
     */
    private Class messageBodyType;

    public String getSenderIp() {
        return senderIp;
    }

    public void setSenderIp(String senderIp) {
        this.senderIp = senderIp;
    }

    public String getServiceId() {
        return serviceId;
    }

    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    public String getMessageGuid() {
        return messageGuid;
    }

    public void setMessageGuid(String messageGuid) {
        this.messageGuid = messageGuid;
    }

    public long getRequestTime() {
        return requestTime;
    }

    public void setRequestTime(long requestTime) {
        this.requestTime = requestTime;
    }

    public Object getMessageBody() {
        return messageBody;
    }

    public void setMessageBody(Object messageBody) {
        this.messageBody = messageBody;
    }

    public Class getMessageBodyType() {
        return messageBodyType;
    }

    public void setMessageBodyType(Class messageBodyType) {
        this.messageBodyType = messageBodyType;
    }

    @Override
    public String toString() {
        return "RequestMessage{" +
                "senderIp='" + senderIp + '\'' +
                ", serviceId='" + serviceId + '\'' +
                ", messageGuid='" + messageGuid + '\'' +
                ", requestTime=" + requestTime +
                ", messageBodyType=" + messageBodyType +
                '}';
    }
}
