package com.nettydemo.not_used.entities;

import java.io.Serializable;

/**
 * Wrapper for messages sent from server to client
 * Contains header and object that being sent (message body)
 */
public class ResponseMessage implements Serializable, Cloneable {
    /**
     * Client IP
     */
    private String senderIp;
    /**
     * Command what server did with the incoming object
     */
    private String serviceId;
    /**
     * Unique code of the message. It is generated by Utils singleton object
     */
    private String messageGuid;
    /**
     * Date and time when the answer was sent
     */
    private long responseTime;
    /**
     * Indicates success or failure ('S' or 'F" accordingly)
     */
    private char responseCode;
    /**
     * Content. The object that is being sent to the server
     */
    private Object messageBody;
    /**
     * Class of the content above. This field is optional, as we can
     * detect content's class by .getClass or instanceOf methods
     */
    private Class messageBodyType;

    public String getSenderIp() {
        return senderIp;
    }

    public void setSenderIp(String senderIp) {
        this.senderIp = senderIp;
    }

    public String getServiceId() {
        return serviceId;
    }

    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    public String getMessageGuid() {
        return messageGuid;
    }

    public void setMessageGuid(String messageGuid) {
        this.messageGuid = messageGuid;
    }

    public long getResponseTime() {
        return responseTime;
    }

    public void setResponseTime(long responseTime) {
        this.responseTime = responseTime;
    }

    public char getResponseCode() {
        return responseCode;
    }

    public void setResponseCode(char responseCode) {
        this.responseCode = responseCode;
    }

    public Object getMessageBody() {
        return messageBody;
    }

    public void setMessageBody(Object messageBody) {
        this.messageBody = messageBody;
    }

    public Class getMessageBodyType() {
        return messageBodyType;
    }

    public void setMessageBodyType(Class messageBodyType) {
        this.messageBodyType = messageBodyType;
    }

    @Override
    public String toString() {
        return "ResponseMessage{" +
                "senderIp='" + senderIp + '\'' +
                ", serviceId='" + serviceId + '\'' +
                ", messageGuid='" + messageGuid + '\'' +
                ", responseTime=" + responseTime +
                ", responseCode=" + responseCode +
                ", messageBodyType=" + messageBodyType +
                '}';
    }
}
